In [ ]:
import pandas as pd

pd.set_option("display.max_colwidth", None)

df = pd.read_json("model_experiments_1.jsonl", lines=True)
df.head()

,channels,ff_factor,example_size,epochs,batch_size,last_ten_losses,params,time_s,fit_steps,out_of_memory,error
0,32,8,128,100,64,"[3.2644, 3.2624, 3.2580, 3.2553, 3.2483, 3.2436, 3.2302, 3.2210, 3.1953, 3.1566, 3.1315, 3.0720, 3.0410, 2.9949, 2.9830, 2.9681, 2.9454, 2.9304, 2.9034, 2.8928, 2.8794, 2.8749, 2.8666, 2.8616, 2.8499, 2.8369, 2.8306, 2.8181, 2.8119, 2.8000, 2.7941, 2.7813, 2.7674, 2.7601, 2.7439, 2.7352, 2.7172, 2.7083, 2.6905, 2.6808, 2.6607, 2.6394, 2.6281, 2.6043, 2.5913, 2.5640, 2.5488, 2.5161, 2.4799, 2.4601, 2.4195, 2.3972, 2.3522, 2.3281, 2.2795, 2.2558, 2.2127, 2.1682, 2.1439, 2.1013, 2.0798, 2.0322, 2.0074, 1.9642, 1.9187, 1.8976, 1.8541, 1.8264, 1.7813, 1.7602, 1.7075, 1.6829, 1.6366, 1.5872, 1.5663, 1.5238, 1.5025, 1.4602, 1.4423, 1.4055, 1.3639, 1.3449, 1.3041, 1.2861, 1.2567, 1.2299, 1.2011, 1.1771, 1.1505, 1.1089, 1.0959, 1.0574, 1.0514, 1.0072, 0.9960, 0.9607, 0.9349, 0.9125, 0.8854, 0.8703, ...]",2242,41.598085,NaN,False,NaN
1,32,8,256,100,64,"[3.2548, 3.2535, 3.2503, 3.2487, 3.2449, 3.2424, 3.2355, 3.2308, 3.2179, 3.1993, 3.1879, 3.1614, 3.1469, 3.1244, 3.1211, 3.1222, 3.1144, 3.1068, 3.0951, 3.0908, 3.0842, 3.0818, 3.0776, 3.0755, 3.0721, 3.0680, 3.0653, 3.0609, 3.0582, 3.0519, 3.0491, 3.0437, 3.0392, 3.0365, 3.0277, 3.0241, 3.0169, 3.0129, 3.0041, 2.9993, 2.9902, 2.9800, 2.9739, 2.9616, 2.9544, 2.9423, 2.9360, 2.9194, 2.9049, 2.8969, 2.8798, 2.8688, 2.8502, 2.8412, 2.8212, 2.8107, 2.7909, 2.7701, 2.7599, 2.7407, 2.7309, 2.7096, 2.6976, 2.6754, 2.6566, 2.6415, 2.6161, 2.6040, 2.5944, 2.5794, 2.5452, 2.5463, 2.5170, 2.4853, 2.4790, 2.4567, 2.4383, 2.4190, 2.4151, 2.3841, 2.3589, 2.3592, 2.3380, 2.3431, 2.3125, 2.2855, 2.2791, 2.2881, 2.2516, 2.2289, 2.2288, 2.1938, 2.1823, 2.1652, 2.1522, 2.1340, 2.1165, 2.1017, 2.0871, 2.0830, ...]",2242,114.497702,NaN,False,NaN
2,32,8,512,100,64,"[3.2985, 3.2978, 3.2959, 3.2948, 3.2922, 3.2904, 3.2865, 3.2838, 3.2764, 3.2650, 3.2576, 3.2393, 3.2286, 3.2072, 3.1992, 3.1891, 3.1838, 3.1822, 3.1814, 3.1775, 3.1685, 3.1654, 3.1638, 3.1645, 3.1632, 3.1589, 3.1567, 3.1516, 3.1496, 3.1468, 3.1453, 3.1419, 3.1392, 3.1381, 3.1345, 3.1319, 3.1291, 3.1291, 3.1273, 3.1257, 3.1196, 3.1116, 3.1085, 3.1023, 3.0991, 3.0937, 3.0907, 3.0834, 3.0745, 3.0703, 3.0665, 3.0633, 3.0490, 3.0433, 3.0340, 3.0286, 3.0165, 3.0040, 2.9985, 2.9877, 2.9824, 2.9730, 2.9679, 2.9583, 2.9469, 2.9421, 2.9326, 2.9277, 2.9183, 2.9133, 2.9048, 2.9010, 2.8925, 2.8827, 2.8783, 2.8693, 2.8643, 2.8526, 2.8476, 2.8438, 2.8287, 2.8196, 2.8084, 2.8040, 2.7909, 2.7839, 2.7739, 2.7666, 2.7516, 2.7408, 2.7344, 2.7364, 2.7328, 2.7017, 2.6957, 2.7037, 2.6825, 2.6685, 2.6657, 2.6714, ...]",2242,365.103736,NaN,False,NaN
3,32,8,128,100,64,"[0.4258, 0.4201, 0.3927, 0.3770, 0.3633, 0.3422, 0.3331, 0.3137, 0.3020, 0.2874]",2242,42.491642,NaN,False,NaN
4,32,8,256,100,64,"[0.2920, 0.2896, 0.2959, 0.2675, 0.2778, 0.2689, 0.2610, 0.2574, 0.2602, 0.2396]",2242,114.669832,NaN,False,NaN

In [ ]:
df_params_fit = df[["params", "example_size", "last_ten_losses", "fit_steps"]].copy()
df_params_fit["loss"] = df_params_fit["last_ten_losses"].apply(
    lambda losses: losses[-1]
)
df_params_fit = df_params_fit.drop(columns=["last_ten_losses"])

In [44]:
df_params_fit.head(20)

    params  example_size  fit_steps    loss
0     2242           128        NaN  0.4995
1     2242           256        NaN  0.4150
2     2242           512        NaN  0.3682
3     2242           128        NaN  0.2874
4     2242           256        NaN  0.2396
5     2242           512        NaN  0.1726
6     2242          1024        NaN  0.3707
7     4290           128    10800.0  0.0008
8     4290           256    23700.0  0.0023
9     4290           512        NaN  0.0261
10    4290          1024        NaN  0.0691
11    8386           128     7500.0  0.0002
12    8386           256    24800.0  0.0029
13    8386           512        NaN  0.0326
14    8386          1024    95500.0  0.0017
15   16578           128     6800.0  0.0000
16   16578           256    15300.0  0.0002
17   16578           512    41000.0  0.0180
18   16578          1024    74000.0  0.0200
19    4354           128    11600.0  0.0012

In [ ]:
from dataclasses import dataclass


@dataclass
class PerParams:




for row in df_params_fit.iterrows():
    params = row[1]["params"]
    fit = row[1]["fit_steps"]
    examples = row[1]["example_size"]
    loss = row[1]["loss"]

params            2242
example_size       128
fit_steps          NaN
loss            0.4995
Name: 0, dtype: object
params            2242
example_size       256
fit_steps          NaN
loss            0.4150
Name: 1, dtype: object
params            2242
example_size       512
fit_steps          NaN
loss            0.3682
Name: 2, dtype: object
params            2242
example_size       128
fit_steps          NaN
loss            0.2874
Name: 3, dtype: object
params            2242
example_size       256
fit_steps          NaN
loss            0.2396
Name: 4, dtype: object
params            2242
example_size       512
fit_steps          NaN
loss            0.1726
Name: 5, dtype: object
params            2242
example_size      1024
fit_steps          NaN
loss            0.3707
Name: 6, dtype: object
params             4290
example_size        128
fit_steps       10800.0
loss             0.0008
Name: 7, dtype: object
params             4290
example_size        256
fit_steps       23700.0
loss             0.0023
Name: 8, dtype: object
params            4290
example_size       512
fit_steps          NaN
loss            0.0261
Name: 9, dtype: object
params            4290
example_size      1024
fit_steps          NaN
loss            0.0691
Name: 10, dtype: object
params            8386
example_size       128
fit_steps       7500.0
loss            0.0002
Name: 11, dtype: object
params             8386
example_size        256
fit_steps       24800.0
loss             0.0029
Name: 12, dtype: object
params            8386
example_size       512
fit_steps          NaN
loss            0.0326
Name: 13, dtype: object
params             8386
example_size       1024
fit_steps       95500.0
loss             0.0017
Name: 14, dtype: object
params           16578
example_size       128
fit_steps       6800.0
loss            0.0000
Name: 15, dtype: object
params            16578
example_size        256
fit_steps       15300.0
loss             0.0002
Name: 16, dtype: object
params            16578
example_size        512
fit_steps       41000.0
loss             0.0180
Name: 17, dtype: object
params            16578
example_size       1024
fit_steps       74000.0
loss             0.0200
Name: 18, dtype: object
params             4354
example_size        128
fit_steps       11600.0
loss             0.0012
Name: 19, dtype: object
params             4354
example_size        256
fit_steps       23300.0
loss             0.0031
Name: 20, dtype: object
params             4354
example_size        512
fit_steps       50600.0
loss             0.0076
Name: 21, dtype: object
params            4354
example_size      1024
fit_steps          NaN
loss            0.0310
Name: 22, dtype: object
params            8450
example_size       128
fit_steps       6900.0
loss            0.0001
Name: 23, dtype: object
params             8450
example_size        256
fit_steps       20000.0
loss             0.0002
Name: 24, dtype: object
params             8450
example_size        512
fit_steps       42400.0
loss             0.0001
Name: 25, dtype: object
params            8450
example_size      1024
fit_steps          NaN
loss            0.0256
Name: 26, dtype: object
params           16642
example_size       128
fit_steps       5700.0
loss            0.0000
Name: 27, dtype: object
params            16642
example_size        256
fit_steps       13800.0
loss             0.0001
Name: 28, dtype: object
params            16642
example_size        512
fit_steps       32800.0
loss             0.0001
Name: 29, dtype: object
params            16642
example_size       1024
fit_steps       94000.0
loss             0.0068
Name: 30, dtype: object
params           33026
example_size       128
fit_steps       6600.0
loss            0.0012
Name: 31, dtype: object
params            33026
example_size        256
fit_steps       15100.0
loss             0.0031
Name: 32, dtype: object
params            33026
example_size        512
fit_steps       32600.0
loss             0.0160
Name: 33, dtype: object
params            33026
example_size       1024
fit_steps       81500.0
loss             0.0181
Name: 34, dtype: object
params            8578
example_size       128
fit_steps       7500.0
loss            0.0001
Name: 35, dtype: object
params             8578
example_size        256
fit_steps       15600.0
loss             0.0002
Name: 36, dtype: object
params             8578
example_size        512
fit_steps       44100.0
loss             0.0329
Name: 37, dtype: object
params            8578
example_size      1024
fit_steps          NaN
loss            0.0452
Name: 38, dtype: object
params           16770
example_size       128
fit_steps       6900.0
loss            0.0000
Name: 39, dtype: object
params            16770
example_size        256
fit_steps       17300.0
loss             0.0496
Name: 40, dtype: object
params            16770
example_size        512
fit_steps       40900.0
loss             0.0027
Name: 41, dtype: object
params            16770
example_size       1024
fit_steps       97300.0
loss             0.0612
Name: 42, dtype: object
params           33154
example_size       128
fit_steps       6400.0
loss            0.0000
Name: 43, dtype: object
params            33154
example_size        256
fit_steps       16700.0
loss             0.0012
Name: 44, dtype: object
params            33154
example_size        512
fit_steps       33800.0
loss             0.0079
Name: 45, dtype: object
params            33154
example_size       1024
fit_steps       71200.0
loss             0.0085
Name: 46, dtype: object
params           65922
example_size       128
fit_steps       5800.0
loss            0.0005
Name: 47, dtype: object
params            65922
example_size        256
fit_steps       12800.0
loss             0.0001
Name: 48, dtype: object
params            65922
example_size        512
fit_steps       28400.0
loss             0.0042
Name: 49, dtype: object
params            65922
example_size       1024
fit_steps       77000.0
loss             0.0895
Name: 50, dtype: object